export const ADD_REMINDER = 'ADD_REMINDER';
export const DELETE_REMINDER = 'DELETE_REMINDER';
export const CLEAR_REMINDERS = 'CLEAR_REMINDERS';

export const ADD_STUDENT = 'ADD_STUDENT';
export const REMOVE_STUDENT = 'REMOVE_STUDENT';

export const ADD_COURSE_TO_STUDENT = "ADD_COURSE_TO_STUDENT";
export const REMOVE_COURSE_FROM_STUDENT = "REMOVE_COURSE_FROM_STUDENT";
